name: first

on: push

jobs:
  job1:
     -name: firstjob
      runs-on: ubuntu-latest
      steps:
        -name: stepone
        uses: action/checkout@v2
        -name: steptwo
         run: env| sort
  job2:
      -name: firstjob
      runs-on: windows-latest
      steps:
       -name: stepone
        uses: action/checkout@v2
        -name: steptwo
        run: "get-chaildItem Env:|sort-object name"
